# Setup
title:            office-of-digital-innovation.github.io
tagline:          'CHHS Data'
description:      'California Health & Human Services Agency'
url:              https://office-of-digital-innovation.github.io

author:
  name:           'California Health & Human Services Agency'
  url:            https://github.com/chhsdata/

# Custom vars
github:
  repo:           https://github.com/Office-of-Digital-Innovation/office-of-digital-innovation.github.io
