# Setup
title:            chhsdata.github.io
tagline:          'CHHS Data'
description:      'California Health & Human Services Agency'
url:              https://chhsdata.github.io

author:
  name:           'California Health & Human Services Agency'
  url:            https://github.com/chhsdata/

# Custom vars
github:
  repo:           https://github.com/chhsdata/chhsdata.github.io
